### ISSUE TITLE
Automated Testing on PR

### ISSUE THREAD

**Issue by KJLJon** [starekrow/lockbox#12]
I think some sort of CI should be ran on pull requests
Travis CI is free for open source projects
https://docs.travis-ci.com/user/languages/php/

**Comment by starekrow** [comment]
Agreed; Travis is actually on my roadmap. I’d like to expand coverage on CryptoKey and Secret, too.

**Comment by alexmanno** [comment]
We can use Scrutinizer together with Travis for static inspection and other nice features!

**Comment by starekrow** [comment]
Done and done. I also did the integration on travis.org and stuffed the status badge in the readme.
